---
- name: Install uncomplicated-firewall
  ansible.builtin.apt:
    name:
      - ufw
    update_cache: true
    state: present

- name: Allow incoming ssh traffic
  community.general.ufw:
    rule: allow
    port: ssh

- name: Disallow all incoming traffic
  community.general.ufw:
    rule: deny
    direction: in

- name: Allow all outgoing traffic
  community.general.ufw:
    rule: allow
    direction: out

- name: Disable UFW
  community.general.ufw:
    state: disabled
