---
- name: Make the {{ user }} user on the host
  hosts: all
  gather_facts: false
  become: true

  vars:
    user: nbaron
    user_groups:
      - admin
    disable_sudo_pwd: false

  tasks:
    - name: Ensure group exists
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      loop: "{{ (user_groups + [user]) }}"

    - name: Add the user and attach their groups
      ansible.builtin.user:
        name: "{{ user }}"
        group: "{{ user }}"
        groups: "{{ user_groups }}"
        password: $6$q6x1.YNRMffmt91n$8BfRyvG1lrLx1jK4Kw9xBVWvnx9OCbwcSW.RFfAJnEMAre5pEjcGpgiWyUS9R3TMiIVSw.T5UOO3jayc/Ybdd/
        update_password: on_create
        create_home: true
        shell: /bin/bash
        home: "/home/{{ user }}"

    - name: "Allow admin users to sudo without a password"
      ansible.builtin.lineinfile:
        dest: "/etc/sudoers" # path: in version 2.3
        state: "present"
        regexp: "^%admin"
        line: "%admin ALL=(ALL) NOPASSWD: ALL"
      when: disable_sudo_pwd

    - name: "Add authorized keys"
      ansible.posix.authorized_key:
        user: "{{ user }}"
        key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/homelab_key.pub') }}"
