---
- name: Setup Secure VM machine
  hosts: virtual-machines
  become: true
  roles:
    - updated
    - qemu-agent
    - ssh-hardened
    - unattended-upgrade
    - uncomplicated-firewall
    - crowdsec-agent
    - docker-host
